"""initial migration

Revision ID: 230d01712235
Revises: 0539269a0bcc
Create Date: 2017-06-06 17:37:51.672438

"""

# revision identifiers, used by Alembic.
revision = '230d01712235'
down_revision = '0539269a0bcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('ahead_price', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('delay_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'delay_time')
    op.drop_column('actions', 'ahead_price')
    # ### end Alembic commands ###
