"""initial migration

Revision ID: d2293f5bbfa1
Revises: 230d01712235
Create Date: 2017-06-08 08:42:40.950405

"""

# revision identifiers, used by Alembic.
revision = 'd2293f5bbfa1'
down_revision = '230d01712235'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
